version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: roundcube-pgsql
    restart: unless-stopped
    volumes:
      - ./roundcube-pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - roundcube-net

  roundcube:
    image: roundcubemail:1.6.x-apache
    container_name: roundcube
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://${ROUNDCUBEMAIL_DEFAULT_HOST}
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://${ROUNDCUBEMAIL_SMTP_SERVER}
      - ROUNDCUBE_SKIN=elastic
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=${ROUNDCUBEMAIL_DB_HOST}
      - ROUNDCUBEMAIL_DB_PORT=${ROUNDCUBEMAIL_DB_PORT}
      - ROUNDCUBEMAIL_DB_USER=${ROUNDCUBEMAIL_DB_USER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBEMAIL_DB_PASSWORD}
      - ROUNDCUBEMAIL_DB_NAME=${ROUNDCUBEMAIL_DB_NAME}
    networks:
      - proxy
      - roundcube-net
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.rule=Host(`${TRAEFIK_ROUNDCUBE}`)"
      - "traefik.http.routers.roundcube.entrypoints=https"
      - "traefik.http.routers.roundcube.tls=true"
      - "traefik.http.routers.roundcube.tls.certresolver=mytlschallenge"

networks:
  roundcube-net:
  proxy:
    external: true
