[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$HLbeDP.8$FmfOnbkIxDbQWtw.qNKIr1"
  ]

[http.routers.api]
  rule = "Host(`monitor.claudiofaoro.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
